#ifndef VSLC_H
#define VSLC_H
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

#include "tlhash.h"
#include "nodetypes.h"
#include "ir.h"
#include "y.tab.h"

/* This is generated from the Bison grammar, calls on the Flex specification */
int yyerror ( const char *error );

/* These are defined in the parser generated by Bison */
extern int yylineno;
extern int yylex ( void );
extern char yytext[];
extern int yyparse ( void );

/* Global root node */
extern node_t *root;


#endif
